---
- name: Install Salt Minion
  hosts: all
  become: yes
  handlers:
    - name: restart_minion
      service:
        name: salt-minion
        state: restarted
  tasks:
    - name: Update system
      zypper:
        name: "*"
        state: latest
    - name: Fix keyboard layout
      command: "/usr/bin/localectl set-keymap de-nodeadkeys"
      changed_when: false
    - name: Set timezone
      command: "/usr/bin/timedatectl set-timezone Europe/Berlin"
      changed_when: false
    - name: Disable firewall as we also like to live dangerously
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: Update /etc/hosts
      template:
        src: hosts
        dest: /etc/hosts
    - name: Install Salt Minion
      zypper:
        name: "{{ salt_packages }}"
        state: present
      vars:
        salt_packages:
        - salt-minion
        - python3-pyinotify
    - name: Create Salt Minion configuration
      template:
        src: minion
        dest: /etc/salt/minion
        owner: root
        group: root
        mode: '0640'
    - name: Start Salt Minion
      service:
        name: salt-minion
        state: started
        enabled: true
    - name: Install Apache
      zypper:
        name: apache2
    - name: Stage demo website
      template:
        src: index.html.j2
        dest: /srv/www/htdocs/index.html
        owner: root
        group: root
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true
    - name: Stage beacons configuration
      template:
        src: beacons.conf
        dest: /etc/salt/minion.d/beacons.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart_minion
