---
- name: Install Salt
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Update system
      zypper:
        name: "*"
        state: latest
    - name: Fix keyboard layout
      command: "/usr/bin/localectl set-keymap de-nodeadkeys"
      changed_when: false
    - name: Set timezone
      command: "/usr/bin/timedatectl set-timezone Europe/Berlin"
      changed_when: false
    - name: Disable firewall as we also like to live dangerously
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: Update /etc/hosts
      template:
        src: hosts
        dest: /etc/hosts
    - name: Install Salt
      zypper:
        name: "{{ salt_packages }}"
        state: present
      vars:
        salt_packages:
        - salt-master
    - name: Create reactor configuration
      copy:
        src: templates/reactor.conf
        dest: /etc/salt/master.d/reactor.conf
        owner: root
        group: salt
        mode: '0640'
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: salt
      with_items:
        - /srv/reactor
        - /srv/salt/website
    - name: Create auto-sign state
      copy:
        src: templates/auto-sign.sls
        dest: /srv/reactor/auto-sign.sls
        owner: root
        group: salt
        mode: '0640'
    - name: Create Apache reactor
      copy:
        src: templates/reactor_restart_apache.sls
        dest: /srv/reactor/restart_apache.sls
        owner: root
        group: salt
        mode: '0640'
    - name: Create Apache restart state
      copy:
        src: templates/state_restart_apache.sls
        dest: /srv/salt/restart_apache2.sls
        owner: root
        group: salt
        mode: '0640'
    - name: Create website reactor
      copy:
        src: templates/reactor_restore_website.sls
        dest: /srv/reactor/restore_website.sls
        owner: root
        group: salt
        mode: '0640'
    - name: Create website restore state
      copy:
        src: templates/state_restore_website.sls
        dest: /srv/salt/restore_website.sls
        owner: root
        group: salt
        mode: '0640'
    - name: Create website template
      copy:
        src: templates/website_index.html.j2
        dest: /srv/salt/website/index.html.j2
        owner: root
        group: salt
        mode: '0640'
    - name: Start Salt Master
      service:
        name: salt-master
        state: started
        enabled: true
